"""ai decision sequence

Revision ID: 42c15f25ccc4
Revises: 5278bfbb5e6d
Create Date: 2026-08-31 23:59:19.919925
"""
from alembic import op
import sqlalchemy as sa


revision = '42c15f25ccc4'
down_revision = '5278bfbb5e6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_decisions', sa.Column('sequence', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_ai_decision_per_attempt'), 'ai_decisions', type_='unique')
    op.create_unique_constraint('uq_ai_decision_sequence', 'ai_decisions', ['opportunity_id', 'sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ai_decision_sequence', 'ai_decisions', type_='unique')
    op.create_unique_constraint(op.f('uq_ai_decision_per_attempt'), 'ai_decisions', ['opportunity_id', 'attempt_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('ai_decisions', 'sequence')
    # ### end Alembic commands ###
