"""ref counters

Revision ID: 5278bfbb5e6d
Revises: ea01a33760f7
Create Date: 2026-08-31 23:58:13.510872
"""
from alembic import op
import sqlalchemy as sa


revision = '5278bfbb5e6d'
down_revision = 'ea01a33760f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_counters',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_ref_counters'))
    )
    op.create_foreign_key(op.f('fk_payments_recovers_opportunity_id_recovery_opportunities'), 'payments', 'recovery_opportunities', ['recovers_opportunity_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_subscription_events_recovers_opportunity_id_recovery_opportunities'), 'subscription_events', 'recovery_opportunities', ['recovers_opportunity_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscription_events_recovers_opportunity_id_recovery_opportunities'), 'subscription_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_recovers_opportunity_id_recovery_opportunities'), 'payments', type_='foreignkey')
    op.drop_table('ref_counters')
    # ### end Alembic commands ###
