"""opportunity simulation key

Revision ID: 8da4e15c3971
Revises: 42c15f25ccc4
Create Date: 2026-09-01 00:16:23.257234
"""
from alembic import op
import sqlalchemy as sa


revision = '8da4e15c3971'
down_revision = '42c15f25ccc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_opportunities', sa.Column('simulation_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_recovery_opportunities_simulation_key'), 'recovery_opportunities', ['simulation_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_opportunities_simulation_key'), table_name='recovery_opportunities')
    op.drop_column('recovery_opportunities', 'simulation_key')
    # ### end Alembic commands ###
