"""customer messaging: notification_messages + opt-out

Revision ID: 95f9bb1ba510
Revises: 8da4e15c3971
Create Date: 2026-09-05 19:57:56.613595
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '95f9bb1ba510'
down_revision = '8da4e15c3971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('recipient_masked', sa.String(length=48), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivered_externally', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['recovery_attempts.id'], name=op.f('fk_notification_messages_attempt_id_recovery_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_notification_messages_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_notification_messages_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_messages'))
    )
    op.create_index('ix_messages_opportunity_channel', 'notification_messages', ['opportunity_id', 'channel'], unique=False)
    op.create_index(op.f('ix_notification_messages_attempt_id'), 'notification_messages', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_notification_messages_channel'), 'notification_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_messages_created_at'), 'notification_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_messages_customer_id'), 'notification_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notification_messages_opportunity_id'), 'notification_messages', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_notification_messages_provider_message_id'), 'notification_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_notification_messages_sent_at'), 'notification_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_messages_status'), 'notification_messages', ['status'], unique=False)
    op.add_column('customers', sa.Column('messaging_opt_out', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'messaging_opt_out')
    op.drop_index(op.f('ix_notification_messages_status'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_sent_at'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_provider_message_id'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_opportunity_id'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_customer_id'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_created_at'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_channel'), table_name='notification_messages')
    op.drop_index(op.f('ix_notification_messages_attempt_id'), table_name='notification_messages')
    op.drop_index('ix_messages_opportunity_channel', table_name='notification_messages')
    op.drop_table('notification_messages')
    # ### end Alembic commands ###
