"""initial schema

Revision ID: ea01a33760f7
Revises: 
Create Date: 2026-08-31 23:38:45.981760
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ea01a33760f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_ref', sa.String(length=64), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_mode', sa.String(length=24), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=24), nullable=False),
    sa.Column('data_version', sa.String(length=24), nullable=False),
    sa.Column('policy_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    op.create_index(op.f('ix_simulation_runs_created_at'), 'simulation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulation_runs_run_ref'), 'simulation_runs', ['run_ref'], unique=True)
    op.create_index(op.f('ix_simulation_runs_status'), 'simulation_runs', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_audit_logs_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_simulation_run_id'), 'audit_logs', ['simulation_run_id'], unique=False)
    op.create_table('baseline_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_baseline_results_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline_results')),
    sa.UniqueConstraint('simulation_run_id', 'strategy', name='uq_baseline_per_run')
    )
    op.create_index(op.f('ix_baseline_results_created_at'), 'baseline_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_baseline_results_simulation_run_id'), 'baseline_results', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_baseline_results_strategy'), 'baseline_results', ['strategy'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_ref', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('previous_transaction_count', sa.Integer(), nullable=False),
    sa.Column('previous_success_count', sa.Integer(), nullable=False),
    sa.Column('previous_failure_count', sa.Integer(), nullable=False),
    sa.Column('historical_success_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('average_order_value_minor', sa.BigInteger(), nullable=False),
    sa.Column('lifetime_value_minor', sa.BigInteger(), nullable=False),
    sa.Column('preferred_payment_method', sa.String(length=32), nullable=True),
    sa.Column('previous_checkout_count', sa.Integer(), nullable=False),
    sa.Column('previous_checkout_conversions', sa.Integer(), nullable=False),
    sa.Column('previous_checkout_conversion_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('previous_subscription_count', sa.Integer(), nullable=False),
    sa.Column('previous_subscription_failures', sa.Integer(), nullable=False),
    sa.Column('previous_recoveries', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_customers_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_customer_ref'), 'customers', ['customer_ref'], unique=True)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_index(op.f('ix_customers_simulation_run_id'), 'customers', ['simulation_run_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_orders_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_id'], unique=False)
    op.create_index(op.f('ix_orders_order_ref'), 'orders', ['order_ref'], unique=True)
    op.create_index(op.f('ix_orders_simulation_run_id'), 'orders', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_orders_source'), 'orders', ['source'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('billing_cycle', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('current_renewal_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('previous_successful_renewals', sa.Integer(), nullable=False),
    sa.Column('previous_failed_renewals', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_subscriptions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_subscriptions_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_id'), 'subscriptions', ['external_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_simulation_run_id'), 'subscriptions', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_source'), 'subscriptions', ['source'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_ref'), 'subscriptions', ['subscription_ref'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_ref', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('is_recovery_payment', sa.Boolean(), nullable=False),
    sa.Column('recovers_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payments_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovers_opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_payments_recovers_opportunity_id_recovery_opportunities'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_payments_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=False)
    op.create_index(op.f('ix_payments_failure_category'), 'payments', ['failure_category'], unique=False)
    op.create_index(op.f('ix_payments_is_recovery_payment'), 'payments', ['is_recovery_payment'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_occurred_at'), 'payments', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_ref'), 'payments', ['payment_ref'], unique=True)
    op.create_index(op.f('ix_payments_recovers_opportunity_id'), 'payments', ['recovers_opportunity_id'], unique=False)
    op.create_index(op.f('ix_payments_simulation_run_id'), 'payments', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_payments_source'), 'payments', ['source'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_category', 'payments', ['status', 'failure_category'], unique=False)
    op.create_table('subscription_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('renewal_ref', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('is_recovery_renewal', sa.Boolean(), nullable=False),
    sa.Column('recovers_opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_subscription_events_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovers_opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_subscription_events_recovers_opportunity_id_recovery_opportunities'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_events_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_events'))
    )
    op.create_index(op.f('ix_subscription_events_created_at'), 'subscription_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_events_customer_id'), 'subscription_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_event_type'), 'subscription_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_subscription_events_failure_category'), 'subscription_events', ['failure_category'], unique=False)
    op.create_index(op.f('ix_subscription_events_is_recovery_renewal'), 'subscription_events', ['is_recovery_renewal'], unique=False)
    op.create_index(op.f('ix_subscription_events_recovers_opportunity_id'), 'subscription_events', ['recovers_opportunity_id'], unique=False)
    op.create_index(op.f('ix_subscription_events_renewal_ref'), 'subscription_events', ['renewal_ref'], unique=True)
    op.create_index(op.f('ix_subscription_events_subscription_id'), 'subscription_events', ['subscription_id'], unique=False)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checkout_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('cart_value_minor', sa.BigInteger(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('products', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('abandonment_reason', sa.String(length=64), nullable=True),
    sa.Column('payment_method_intended', sa.String(length=32), nullable=True),
    sa.Column('completed_payment_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_payment_id'], ['payments.id'], name=op.f('fk_checkout_sessions_completed_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_checkout_sessions_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_checkout_sessions_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_checkout_sessions_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkout_sessions'))
    )
    op.create_index(op.f('ix_checkout_sessions_abandoned_at'), 'checkout_sessions', ['abandoned_at'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_checkout_ref'), 'checkout_sessions', ['checkout_ref'], unique=True)
    op.create_index(op.f('ix_checkout_sessions_created_at'), 'checkout_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_customer_id'), 'checkout_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_external_id'), 'checkout_sessions', ['external_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_simulation_run_id'), 'checkout_sessions', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_source'), 'checkout_sessions', ['source'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_status'), 'checkout_sessions', ['status'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_events_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index(op.f('ix_payment_events_created_at'), 'payment_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    op.create_table('recovery_opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_ref', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('checkout_session_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_event_id', sa.Uuid(), nullable=True),
    sa.Column('amount_at_risk_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failure_category', sa.String(length=48), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('recovered_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projected_retention_minor', sa.BigInteger(), nullable=False),
    sa.Column('context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_recovery_opportunities_attempt_count_non_negative')),
    sa.CheckConstraint('recovered_amount_minor >= 0 AND recovered_amount_minor <= amount_at_risk_minor', name=op.f('ck_recovery_opportunities_recovered_within_risk')),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], name=op.f('fk_recovery_opportunities_checkout_session_id_checkout_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_recovery_opportunities_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_recovery_opportunities_payment_id_payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_recovery_opportunities_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_event_id'], ['subscription_events.id'], name=op.f('fk_recovery_opportunities_subscription_event_id_subscription_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_recovery_opportunities_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_opportunities'))
    )
    op.create_index('ix_opportunities_run_scenario', 'recovery_opportunities', ['simulation_run_id', 'scenario'], unique=False)
    op.create_index('ix_opportunities_scenario_status', 'recovery_opportunities', ['scenario', 'status'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_checkout_session_id'), 'recovery_opportunities', ['checkout_session_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_created_at'), 'recovery_opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_customer_id'), 'recovery_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_dedupe_key'), 'recovery_opportunities', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_recovery_opportunities_failure_category'), 'recovery_opportunities', ['failure_category'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_opportunity_ref'), 'recovery_opportunities', ['opportunity_ref'], unique=True)
    op.create_index(op.f('ix_recovery_opportunities_payment_id'), 'recovery_opportunities', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_scenario'), 'recovery_opportunities', ['scenario'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_simulation_run_id'), 'recovery_opportunities', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_source'), 'recovery_opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_status'), 'recovery_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_subscription_event_id'), 'recovery_opportunities', ['subscription_event_id'], unique=False)
    op.create_index(op.f('ix_recovery_opportunities_subscription_id'), 'recovery_opportunities', ['subscription_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('decision_source', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('context_signature', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_ai_decisions_confidence_range')),
    sa.CheckConstraint('recovery_probability >= 0 AND recovery_probability <= 1', name=op.f('ck_ai_decisions_probability_range')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_ai_decisions_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decisions')),
    sa.UniqueConstraint('opportunity_id', 'attempt_number', name='uq_ai_decision_per_attempt')
    )
    op.create_index(op.f('ix_ai_decisions_action'), 'ai_decisions', ['action'], unique=False)
    op.create_index(op.f('ix_ai_decisions_context_signature'), 'ai_decisions', ['context_signature'], unique=False)
    op.create_index(op.f('ix_ai_decisions_created_at'), 'ai_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_decisions_decision_source'), 'ai_decisions', ['decision_source'], unique=False)
    op.create_index(op.f('ix_ai_decisions_opportunity_id'), 'ai_decisions', ['opportunity_id'], unique=False)
    op.create_table('simulation_ground_truth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('action_success_probs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('latent_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('optimal_action', sa.String(length=48), nullable=False),
    sa.Column('optimal_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_recoverable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_simulation_ground_truth_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_simulation_ground_truth_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_ground_truth')),
    sa.UniqueConstraint('opportunity_id', name=op.f('uq_simulation_ground_truth_opportunity_id'))
    )
    op.create_index(op.f('ix_simulation_ground_truth_created_at'), 'simulation_ground_truth', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulation_ground_truth_simulation_run_id'), 'simulation_ground_truth', ['simulation_run_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processing_status', sa.String(length=24), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_webhook_events_opportunity_id_recovery_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_processing_status'), 'webhook_events', ['processing_status'], unique=False)
    op.create_index('ix_webhook_received', 'webhook_events', ['received_at'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('ai_decision_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=24), nullable=False),
    sa.Column('requested_action', sa.String(length=48), nullable=False),
    sa.Column('effective_action', sa.String(length=48), nullable=True),
    sa.Column('blocked_by_rule', sa.String(length=48), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rules_evaluated', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['ai_decisions.id'], name=op.f('fk_policy_decisions_ai_decision_id_ai_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_policy_decisions_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decisions')),
    sa.UniqueConstraint('opportunity_id', 'ai_decision_id', name='uq_policy_per_ai_decision')
    )
    op.create_index(op.f('ix_policy_decisions_ai_decision_id'), 'policy_decisions', ['ai_decision_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_blocked_by_rule'), 'policy_decisions', ['blocked_by_rule'], unique=False)
    op.create_index(op.f('ix_policy_decisions_created_at'), 'policy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_opportunity_id'), 'policy_decisions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_verdict'), 'policy_decisions', ['verdict'], unique=False)
    op.create_table('recovery_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_ref', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('ai_decision_id', sa.Uuid(), nullable=True),
    sa.Column('policy_decision_id', sa.Uuid(), nullable=True),
    sa.Column('executor', sa.String(length=32), nullable=False),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=True),
    sa.Column('attribution_token', sa.String(length=128), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_decision_id'], ['ai_decisions.id'], name=op.f('fk_recovery_attempts_ai_decision_id_ai_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_recovery_attempts_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], name=op.f('fk_recovery_attempts_policy_decision_id_policy_decisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_attempts')),
    sa.UniqueConstraint('opportunity_id', 'attempt_number', name='uq_attempt_number')
    )
    op.create_index(op.f('ix_recovery_attempts_action'), 'recovery_attempts', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_attempt_ref'), 'recovery_attempts', ['attempt_ref'], unique=True)
    op.create_index(op.f('ix_recovery_attempts_attribution_token'), 'recovery_attempts', ['attribution_token'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_created_at'), 'recovery_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_executed_at'), 'recovery_attempts', ['executed_at'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_execution_status'), 'recovery_attempts', ['execution_status'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_external_ref'), 'recovery_attempts', ['external_ref'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_opportunity_id'), 'recovery_attempts', ['opportunity_id'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('realized_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('evidence_ref', sa.String(length=128), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('realized_amount_minor >= 0', name=op.f('ck_recovery_outcomes_realized_non_negative')),
    sa.ForeignKeyConstraint(['attempt_id'], ['recovery_attempts.id'], name=op.f('fk_recovery_outcomes_attempt_id_recovery_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_recovery_outcomes_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_outcomes')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_recovery_outcomes_attempt_id'))
    )
    op.create_index(op.f('ix_recovery_outcomes_created_at'), 'recovery_outcomes', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_evidence_ref'), 'recovery_outcomes', ['evidence_ref'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_opportunity_id'), 'recovery_outcomes', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recovery_outcomes_outcome'), 'recovery_outcomes', ['outcome'], unique=False)
    op.create_table('recovery_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('simulation_run_id', sa.Uuid(), nullable=True),
    sa.Column('scenario', sa.String(length=48), nullable=False),
    sa.Column('original_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('recovered_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('settlement_key', sa.String(length=255), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recovered_amount_minor > 0 AND recovered_amount_minor <= original_amount_minor', name=op.f('ck_recovery_ledger_recovered_within_original')),
    sa.ForeignKeyConstraint(['attempt_id'], ['recovery_attempts.id'], name=op.f('fk_recovery_ledger_attempt_id_recovery_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['recovery_opportunities.id'], name=op.f('fk_recovery_ledger_opportunity_id_recovery_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['recovery_outcomes.id'], name=op.f('fk_recovery_ledger_outcome_id_recovery_outcomes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], name=op.f('fk_recovery_ledger_simulation_run_id_simulation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_ledger')),
    sa.UniqueConstraint('settlement_key', name=op.f('uq_recovery_ledger_settlement_key'))
    )
    op.create_index(op.f('ix_recovery_ledger_created_at'), 'recovery_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_recovery_ledger_opportunity_id'), 'recovery_ledger', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_recovery_ledger_scenario'), 'recovery_ledger', ['scenario'], unique=False)
    op.create_index(op.f('ix_recovery_ledger_settled_at'), 'recovery_ledger', ['settled_at'], unique=False)
    op.create_index(op.f('ix_recovery_ledger_simulation_run_id'), 'recovery_ledger', ['simulation_run_id'], unique=False)
    op.create_index(op.f('ix_recovery_ledger_source'), 'recovery_ledger', ['source'], unique=False)
    op.create_index('uq_ledger_one_recovery_per_opportunity', 'recovery_ledger', ['opportunity_id'], unique=True, postgresql_where=sa.text("entry_type = 'RECOVERED'"), sqlite_where=sa.text("entry_type = 'RECOVERED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_one_recovery_per_opportunity', table_name='recovery_ledger', postgresql_where=sa.text("entry_type = 'RECOVERED'"), sqlite_where=sa.text("entry_type = 'RECOVERED'"))
    op.drop_index(op.f('ix_recovery_ledger_source'), table_name='recovery_ledger')
    op.drop_index(op.f('ix_recovery_ledger_simulation_run_id'), table_name='recovery_ledger')
    op.drop_index(op.f('ix_recovery_ledger_settled_at'), table_name='recovery_ledger')
    op.drop_index(op.f('ix_recovery_ledger_scenario'), table_name='recovery_ledger')
    op.drop_index(op.f('ix_recovery_ledger_opportunity_id'), table_name='recovery_ledger')
    op.drop_index(op.f('ix_recovery_ledger_created_at'), table_name='recovery_ledger')
    op.drop_table('recovery_ledger')
    op.drop_index(op.f('ix_recovery_outcomes_outcome'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_opportunity_id'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_evidence_ref'), table_name='recovery_outcomes')
    op.drop_index(op.f('ix_recovery_outcomes_created_at'), table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index(op.f('ix_recovery_attempts_opportunity_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_external_ref'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_execution_status'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_executed_at'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_created_at'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_attribution_token'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_attempt_ref'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_action'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index(op.f('ix_policy_decisions_verdict'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_opportunity_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_created_at'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_blocked_by_rule'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_ai_decision_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index('ix_webhook_received', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processing_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_created_at'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_simulation_ground_truth_simulation_run_id'), table_name='simulation_ground_truth')
    op.drop_index(op.f('ix_simulation_ground_truth_created_at'), table_name='simulation_ground_truth')
    op.drop_table('simulation_ground_truth')
    op.drop_index(op.f('ix_ai_decisions_opportunity_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_decision_source'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_created_at'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_context_signature'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_action'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_recovery_opportunities_subscription_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_subscription_event_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_status'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_source'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_simulation_run_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_scenario'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_payment_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_opportunity_ref'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_failure_category'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_dedupe_key'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_customer_id'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_created_at'), table_name='recovery_opportunities')
    op.drop_index(op.f('ix_recovery_opportunities_checkout_session_id'), table_name='recovery_opportunities')
    op.drop_index('ix_opportunities_scenario_status', table_name='recovery_opportunities')
    op.drop_index('ix_opportunities_run_scenario', table_name='recovery_opportunities')
    op.drop_table('recovery_opportunities')
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_created_at'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_checkout_sessions_status'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_source'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_simulation_run_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_external_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_customer_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_created_at'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_checkout_ref'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_abandoned_at'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index(op.f('ix_subscription_events_subscription_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_renewal_ref'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_recovers_opportunity_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_is_recovery_renewal'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_failure_category'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_event_type'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_customer_id'), table_name='subscription_events')
    op.drop_index(op.f('ix_subscription_events_created_at'), table_name='subscription_events')
    op.drop_table('subscription_events')
    op.drop_index('ix_payments_status_category', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_source'), table_name='payments')
    op.drop_index(op.f('ix_payments_simulation_run_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_recovers_opportunity_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_occurred_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_is_recovery_payment'), table_name='payments')
    op.drop_index(op.f('ix_payments_failure_category'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_subscription_ref'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_source'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_simulation_run_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_source'), table_name='orders')
    op.drop_index(op.f('ix_orders_simulation_run_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_ref'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_simulation_run_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_ref'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_baseline_results_strategy'), table_name='baseline_results')
    op.drop_index(op.f('ix_baseline_results_simulation_run_id'), table_name='baseline_results')
    op.drop_index(op.f('ix_baseline_results_created_at'), table_name='baseline_results')
    op.drop_table('baseline_results')
    op.drop_index(op.f('ix_audit_logs_simulation_run_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_simulation_runs_status'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_run_ref'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_created_at'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
